create table public.payment (
    payment_id bigint generated by default as identity primary key,

    reservation_id bigint not null
        references public.reservation(reservation_id),

    payment_method text not null,

    amount numeric(12, 2) not null,

    paid_at timestamptz not null default now(),

    bill_to_partner_id bigint
        references public.partner(partner_id),

    constraint chk_payment_method
        check (
            payment_method in (
                '현금',
                '카드',
                '후불'
            )
        ),

    constraint chk_payment_amount
        check (amount > 0),

    constraint chk_payment_partner
        check (
            (
                payment_method = '후불'
                and bill_to_partner_id is not null
            )
            or
            (
                payment_method in ('현금', '카드')
                and bill_to_partner_id is null
            )
        )
);

-- 조회 성능용 인덱스
create index idx_payment_reservation
on public.payment(reservation_id);

create index idx_payment_paid_at
on public.payment(paid_at);

create index idx_payment_partner
on public.payment(bill_to_partner_id);
