create table public.charge_item (
    charge_item_id bigint generated by default as identity primary key,

    property_id bigint not null
        references public.property(property_id),

    item_name text not null,

    default_price numeric(12, 2) not null default 0,

    is_active boolean not null default true,

    constraint chk_charge_item_price
        check (default_price >= 0),

    constraint uq_charge_item
        unique (property_id, item_name)
);
