create table public.reservation_room (
    reservation_room_id bigint generated by default as identity primary key,

    reservation_id bigint not null
        references public.reservation(reservation_id)
        on delete cascade,

    room_type_id bigint not null
        references public.room_type(room_type_id),

    room_id bigint
        references public.room(room_id),

    -- 예약 내 개별 객실의 숙박 진행 상태
    stay_status text not null default '예약'
        check (stay_status in ('예약', '재실', '퇴실', '취소')),

    rate_amount numeric(12, 2) not null default 0,

    constraint chk_room_rate_amount
        check (rate_amount >= 0)
);

-- 조회 성능용 인덱스
create index idx_reservation_room_reservation
on public.reservation_room(reservation_id);

create index idx_reservation_room_room
on public.reservation_room(room_id);

create index idx_reservation_room_type
on public.reservation_room(room_type_id);
