create table public.room_type (
    room_type_id bigint generated by default as identity primary key,
    property_id bigint not null
        references public.property(property_id),
    room_type_name text not null,

    constraint uq_room_type
        unique (property_id, room_type_name)
);
