create table public.reservation (
    reservation_id bigint generated by default as identity primary key,

    property_id bigint not null
        references public.property(property_id),

    customer_id bigint not null
        references public.customer(customer_id),

    booking_partner_id bigint
        references public.partner(partner_id),

    check_in date not null,
    check_out date not null,

    status text not null default '예약',

    note text,

    created_at timestamptz not null default now(),

    constraint chk_reservation_status
        check (
            status in (
                '예약',
                '재실',
                '퇴실',
                '취소'
            )
        ),

    constraint chk_reservation_dates
        check (check_out > check_in)
);

-- 조회 성능용 인덱스
create index idx_reservation_property
on public.reservation(property_id);

create index idx_reservation_customer
on public.reservation(customer_id);

create index idx_reservation_partner
on public.reservation(booking_partner_id);

create index idx_reservation_dates
on public.reservation(
    property_id,
    check_in,
    check_out
);

create index idx_reservation_status
on public.reservation(status);
