CREATE TABLE public.room (
    room_id bigint
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    property_id bigint NOT NULL
        REFERENCES public.property(property_id),

    room_type_id bigint NOT NULL
        REFERENCES public.room_type(room_type_id),

    room_number text NOT NULL,

    housekeeping_status text NOT NULL
        DEFAULT '공실',

    is_out_of_order boolean NOT NULL
        DEFAULT false,

    CONSTRAINT chk_housekeeping_status
        CHECK (
            housekeeping_status IN (
                '공실',
                '재실',
                '미정비'
            )
        ),

    CONSTRAINT uq_room_number
        UNIQUE (property_id, room_number)
);

-- 조회 성능용 인덱스
create index idx_room_property
on public.room(property_id);

create index idx_room_room_type
on public.room(room_type_id);
