create table public.partner (
    partner_id bigint generated by default as identity primary key,

    partner_name text not null,

    partner_type text not null,

    constraint chk_partner_type
        check (
            partner_type in (
                'TBA',
                'OTA',
                '워크인'
            )
        ),

    constraint uq_partner_name
        unique (partner_name)
);
