create table public.reservation_charge (
    reservation_charge_id bigint generated by default as identity primary key,

    reservation_id bigint not null
        references public.reservation(reservation_id)
        on delete cascade,

    charge_item_id bigint not null
        references public.charge_item(charge_item_id),

    quantity integer not null default 1,

    unit_price numeric(12, 2) not null,

    charged_at timestamptz not null default now(),

    constraint chk_charge_quantity
        check (quantity > 0),

    constraint chk_charge_unit_price
        check (unit_price >= 0)
);

-- 조회 성능용 인덱스
create index idx_reservation_charge_reservation
on public.reservation_charge(reservation_id);

create index idx_reservation_charge_item
on public.reservation_charge(charge_item_id);
