CREATE TABLE public.rate_type (
    rate_type_id bigint
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    property_id bigint NOT NULL
        REFERENCES public.property(property_id),

    rate_type_name text NOT NULL,

    CONSTRAINT uq_rate_type_name
        UNIQUE (property_id, rate_type_name)
);

ALTER TABLE public.rate_type ENABLE ROW LEVEL SECURITY;
