SET local check_function_bodies = off;

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE TABLE "public"."charge_item" (
  "charge_item_id" bigint        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "property_id"    bigint        NOT NULL,
  "item_name"      text          NOT NULL,
  "default_price"  numeric(12,2) NOT NULL DEFAULT 0,
  "is_active"      boolean       NOT NULL DEFAULT true,
  CONSTRAINT "charge_item_pkey" PRIMARY KEY (charge_item_id),
  CONSTRAINT "chk_charge_item_price" CHECK ((default_price >= (0)::numeric)),
  CONSTRAINT "uq_charge_item" UNIQUE (property_id, item_name)
);

ALTER TABLE "public"."charge_item"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."customer" (
  "customer_id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "customer_name" text   NOT NULL,
  CONSTRAINT "customer_pkey" PRIMARY KEY (customer_id)
);

ALTER TABLE "public"."customer"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."partner" (
  "partner_id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "partner_name" text   NOT NULL,
  "partner_type" text   NOT NULL,
  CONSTRAINT "chk_partner_type" CHECK ((partner_type = ANY (ARRAY['OTA'::text, 'TBA'::text, '워크인'::text]))),
  CONSTRAINT "partner_pkey" PRIMARY KEY (partner_id),
  CONSTRAINT "uq_partner_name" UNIQUE (partner_name)
);

ALTER TABLE "public"."partner"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."payment" (
  "payment_id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservation_id"     bigint                   NOT NULL,
  "payment_method"     text                     NOT NULL,
  "amount"             numeric(12,2)            NOT NULL,
  "paid_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "bill_to_partner_id" bigint,
  CONSTRAINT "chk_payment_amount" CHECK ((amount > (0)::numeric)),
  CONSTRAINT "chk_payment_method" CHECK ((payment_method = ANY (ARRAY['현금'::text, '카드'::text, '후불'::text]))),
  CONSTRAINT "chk_payment_partner" CHECK ((((payment_method = '후불'::text) AND (bill_to_partner_id IS
    NOT NULL)) OR ((payment_method = ANY (ARRAY['현금'::text, '카드'::text])) AND (bill_to_partner_id IS NULL)))),
  CONSTRAINT "payment_pkey" PRIMARY KEY (payment_id)
);

ALTER TABLE "public"."payment"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."property" (
  "property_id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "property_name" text   NOT NULL,
  CONSTRAINT "property_pkey" PRIMARY KEY (property_id)
);

ALTER TABLE "public"."property"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reservation_charge" (
  "reservation_charge_id" bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservation_id"        bigint                   NOT NULL,
  "charge_item_id"        bigint                   NOT NULL,
  "quantity"              integer                  NOT NULL DEFAULT 1,
  "unit_price"            numeric(12,2)            NOT NULL,
  "charged_at"            timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "chk_charge_quantity" CHECK ((quantity > 0)),
  CONSTRAINT "chk_charge_unit_price" CHECK ((unit_price >= (0)::numeric)),
  CONSTRAINT "reservation_charge_pkey" PRIMARY KEY (reservation_charge_id)
);

ALTER TABLE "public"."reservation_charge"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reservation_ref" (
  "reservation_id" bigint NOT NULL,
  "ref_type"       text   NOT NULL,
  "ref_number"     text   NOT NULL,
  CONSTRAINT "chk_ref_type" CHECK ((ref_type = ANY (ARRAY['INTERNAL'::text, 'EXTERNAL'::text]))),
  CONSTRAINT "reservation_ref_pkey" PRIMARY KEY (reservation_id, ref_type, ref_number)
);

ALTER TABLE "public"."reservation_ref"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reservation_room" (
  "reservation_room_id" bigint        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reservation_id"      bigint        NOT NULL,
  "room_type_id"        bigint        NOT NULL,
  "room_id"             bigint,
  "rate_amount"         numeric(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT "chk_room_rate_amount" CHECK ((rate_amount >= (0)::numeric)),
  CONSTRAINT "reservation_room_pkey" PRIMARY KEY (reservation_room_id)
);

ALTER TABLE "public"."reservation_room"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."reservation" (
  "reservation_id"     bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "property_id"        bigint                   NOT NULL,
  "customer_id"        bigint                   NOT NULL,
  "booking_partner_id" bigint,
  "check_in"           date                     NOT NULL,
  "check_out"          date                     NOT NULL,
  "status"             text                     NOT NULL DEFAULT ' 예약'::text,
  "note"               text,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "chk_reservation_dates" CHECK ((check_out > check_in)),
  CONSTRAINT "chk_reservation_status" CHECK ((status = ANY (ARRAY['예약'::text, '재실'::text, '퇴실'::text, '취소'::text]))),
  CONSTRAINT "reservation_pkey" PRIMARY KEY (reservation_id)
);

ALTER TABLE "public"."reservation"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."room_type" (
  "room_type_id"   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "property_id"    bigint NOT NULL,
  "room_type_name" text   NOT NULL,
  CONSTRAINT "room_type_pkey" PRIMARY KEY (room_type_id),
  CONSTRAINT "uq_room_type" UNIQUE (property_id, room_type_name)
);

ALTER TABLE "public"."room_type"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."room" (
  "room_id"             bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "property_id"         bigint  NOT NULL,
  "room_type_id"        bigint  NOT NULL,
  "room_number"         text    NOT NULL,
  "housekeeping_status" text    NOT NULL DEFAULT '정비완료'::text,
  "is_out_of_order"     boolean NOT NULL DEFAULT false,
  CONSTRAINT "chk_housekeeping_status" CHECK ((housekeeping_status = ANY (ARRAY['공실'::text, '재실'::text, '미정비'::text]))),
  CONSTRAINT "room_pkey" PRIMARY KEY (room_id),
  CONSTRAINT "uq_room_number" UNIQUE (property_id, room_number)
);

ALTER TABLE "public"."room"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.create_internal_reservation_ref()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN

    INSERT INTO public.reservation_ref (
        reservation_id,
        ref_type,
        ref_number
    )
    VALUES (
        NEW.reservation_id,
        'INTERNAL',
        TO_CHAR(NEW.created_at, 'YYYYMMDD')
        || '-'
        || LPAD(NEW.reservation_id::text, 6, '0')
    );

    RETURN NEW;

END;
$function$;

ALTER TABLE "public"."payment"
  ADD CONSTRAINT "payment_bill_to_partner_id_fkey" FOREIGN KEY (bill_to_partner_id) REFERENCES public.partner(partner_id);

ALTER TABLE "public"."charge_item"
  ADD CONSTRAINT "charge_item_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.property(property_id);

ALTER TABLE "public"."reservation"
  ADD CONSTRAINT "reservation_booking_partner_id_fkey" FOREIGN KEY (booking_partner_id) REFERENCES public.partner(partner_id);

ALTER TABLE "public"."reservation"
  ADD CONSTRAINT "reservation_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id);

ALTER TABLE "public"."payment"
  ADD CONSTRAINT "payment_reservation_id_fkey" FOREIGN KEY (reservation_id) REFERENCES public.reservation(reservation_id);

ALTER TABLE "public"."reservation"
  ADD CONSTRAINT "reservation_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.property(property_id);

ALTER TABLE "public"."reservation_charge"
  ADD CONSTRAINT "reservation_charge_charge_item_id_fkey" FOREIGN KEY (charge_item_id) REFERENCES public.charge_item(charge_item_id);

ALTER TABLE "public"."reservation_charge"
  ADD CONSTRAINT "reservation_charge_reservation_id_fkey" FOREIGN KEY (reservation_id) REFERENCES public.reservation(reservation_id) ON DELETE CASCADE;

ALTER TABLE "public"."reservation_ref"
  ADD CONSTRAINT "reservation_ref_reservation_id_fkey" FOREIGN KEY (reservation_id) REFERENCES public.reservation(reservation_id) ON DELETE CASCADE;

ALTER TABLE "public"."reservation_room"
  ADD CONSTRAINT "reservation_room_reservation_id_fkey" FOREIGN KEY (reservation_id) REFERENCES public.reservation(reservation_id) ON DELETE CASCADE;

ALTER TABLE "public"."reservation_room"
  ADD CONSTRAINT "reservation_room_room_id_fkey" FOREIGN KEY (room_id) REFERENCES public.room(room_id);

ALTER TABLE "public"."room"
  ADD CONSTRAINT "room_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.property(property_id);

ALTER TABLE "public"."reservation_room"
  ADD CONSTRAINT "reservation_room_room_type_id_fkey" FOREIGN KEY (room_type_id) REFERENCES public.room_type(room_type_id);

ALTER TABLE "public"."room"
  ADD CONSTRAINT "room_room_type_id_fkey" FOREIGN KEY (room_type_id) REFERENCES public.room_type(room_type_id);

ALTER TABLE "public"."room_type"
  ADD CONSTRAINT "room_type_property_id_fkey" FOREIGN KEY (property_id) REFERENCES public.property(property_id);

CREATE INDEX idx_payment_paid_at ON public.payment USING btree (paid_at);

CREATE INDEX idx_payment_partner ON public.payment USING btree (bill_to_partner_id);

CREATE INDEX idx_payment_reservation ON public.payment USING btree (reservation_id);

CREATE INDEX idx_reservation_charge_item ON public.reservation_charge USING btree (charge_item_id);

CREATE INDEX idx_reservation_charge_reservation ON public.reservation_charge USING btree (reservation_id);

CREATE INDEX idx_reservation_customer ON public.reservation USING btree (customer_id);

CREATE INDEX idx_reservation_dates ON public.reservation USING btree (property_id, check_in, check_out);

CREATE INDEX idx_reservation_partner ON public.reservation USING btree (booking_partner_id);

CREATE INDEX idx_reservation_property ON public.reservation USING btree (property_id);

CREATE INDEX idx_reservation_ref_number ON public.reservation_ref USING btree (ref_number);

CREATE INDEX idx_reservation_room_reservation ON public.reservation_room USING btree (reservation_id);

CREATE INDEX idx_reservation_room_room ON public.reservation_room USING btree (room_id);

CREATE INDEX idx_reservation_room_type ON public.reservation_room USING btree (room_type_id);

CREATE INDEX idx_reservation_status ON public.reservation USING btree (status);

CREATE INDEX idx_room_property ON public.room USING btree (property_id);

CREATE INDEX idx_room_room_type ON public.room USING btree (room_type_id);

CREATE UNIQUE INDEX uq_reservation_internal_ref ON public.reservation_ref USING btree (reservation_id)
  WHERE (ref_type = 'INTERNAL'::text);

CREATE TRIGGER trg_create_internal_reservation_ref
  AFTER INSERT ON public.reservation
  FOR EACH ROW
  EXECUTE FUNCTION public.create_internal_reservation_ref();

GRANT EXECUTE ON FUNCTION "public"."create_internal_reservation_ref"() TO PUBLIC, "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."charge_item" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."charge_item" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."charge_item" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."customer" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."customer" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."customer" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."partner" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."partner" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."partner" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."payment" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."payment" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."payment" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."property" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."property" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."property" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reservation" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation_charge" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reservation_charge" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation_charge" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation_ref" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reservation_ref" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation_ref" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation_room" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."reservation_room" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."reservation_room" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."room" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."room" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."room" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."room_type" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."room_type" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."room_type" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";

